# Generated by Django 3.2.7 on 2021-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='Nombre producto')),
                ('fechaini', models.DateField(verbose_name='Fecha Inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha Final')),
                ('acta', models.CharField(max_length=254, null=True)),
                ('estado', models.SmallIntegerField(default=0)),
                ('fechareg', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
